version: 2.1

workflows:
 ci-deploy:
  jobs:
    - test 
jobs: 
 test:
  docker: 
   - image: cimg/node:18.3.0
  steps:
    - checkout
    - run: 
       name: Install dependencies
       command: npm install 
    - run:
       name: Start app
       command: npm run test 
      
