version: 2.1

commands:
  error:
    description: "Prints error when first step fails"
    steps: 
    - run: exit 1
         

jobs:
  build:
    docker:
      - image: cimg/node:18.3.0
        # auth:
        #   username: annuore
        #   password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - error
      - run: 
          command: echo "Oops! Failed! Heeeeelllllpppp!!!!"
          when: on_fail